[colors.primary]
background = "#141419"
foreground = "#ffffff"

[font]
size = 12

[cursor]
    style = "Beam"

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "W"
mods = "SUPER"
