theme = "ayu_dark"

[editor]
line-number = "relative"
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w"
C-q = ":wq"

[keys.insert]
A-n = "normal_mode"

[keys.select]
A-n = "normal_mode"
